# Compiler and flags
CC = cc
CFLAGS = -Wall -Wextra -Werror

VPATH = src:./ft_printf:./get_next_line

# Source and object files
SRCS =	ft_atoi.c	\
		ft_bzero.c	\
		ft_calloc.c	\
		ft_isalnum.c \
		ft_isalpha.c \
		ft_isascii.c \
		ft_isdigit.c \
		ft_isprint.c \
		ft_itoa.c	\
		ft_memchr.c \
		ft_memcmp.c \
		ft_memcpy.c \
		ft_memmove.c \
		ft_memset.c \
		ft_putchar_fd.c \
		ft_putendl_fd.c \
		ft_putnbr_fd.c \
		ft_putstr_fd.c \
		ft_split.c \
		ft_strchr.c\
		ft_strdup.c \
		ft_striteri.c \
		ft_strjoin.c \
		ft_strlcat.c \
		ft_strlcpy.c \
		ft_strlen.c \
		ft_strmapi.c \
		ft_strncmp.c \
		ft_strcmp.c	\
		ft_strnstr.c \
		ft_strrchr.c \
		ft_strtrim.c \
		ft_substr.c \
		ft_tolower.c \
		ft_toupper.c \
		ft_printf.c \
		print_char.c \
		print_format.c \
		print_hex_lowercase.c \
		print_hex_uppercase.c \
		print_ptr.c \
		print_signed_decimal.c \
		print_str.c \
		print_unsigned_decimal.c \
		get_next_line.c \
		get_next_line_utils.c\
		ft_atol.c\
		ft_strjoin_free.c\


OBJS = $(SRCS:.c=.o)

# Name of the static library
NAME = libft.a

# Rule to create the static library
$(NAME): $(OBJS)
	ar rcs $(NAME) $(OBJS)

# Rule to compile .c files into .o files
%.o: %.c
	$(CC) $(CFLAGS) -c $^ -o $@

all: $(NAME)
# Clean up object files
clean:
	rm -f $(OBJS)

# Clean up object files and the library
fclean: clean
	rm -f $(NAME)

# Rebuild everything
re: fclean $(NAME)

# Special rule to avoid conflicts with files named 'clean', 'fclean', etc.
.PHONY: all clean fclean re
